name: GH Pages Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    # Ensure test job passes before deploying
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Latest Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Cache Modules
        id: node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4